DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
id SERIAL4 PRIMARY KEY,
name VARCHAR(255),
funds INT8
);

CREATE TABLE films (
id SERIAL4 PRIMARY KEY,
title  VARCHAR(255),
price  INT4
);

CREATE TABLE tickets (
id SERIAL4 PRIMARY KEY,
film_id INT4 REFERENCES films(id) ON DELETE CASCADE,
customer_id INT4 REFERENCES customers(id) ON DELETE CASCADE,
show_time INT4 
);